#!/bin/bash

#
# git-comp: A Simple wrapper script to be used at competitions.
# This script allows the use of an alternate repository.
#

# The competition repository.
USERNAME=git
HOST=192.168.0.100
COMP_REPO=$USERNAME@$HOST:\~/repo

# Add the alt remote
git remote add alt $COMP_REPO

# Fetch the current branch
CURRENT_BRANCH=$(git branch | grep "*" | cut -c 3-)

#
# Add the alt options
#
if [ "$1" == "push" ]; then
    git push alt $CURRENT_BRANCH
elif [ "$1" == "pull" ]; then
    git pull alt $CURRENT_BRANCH
else
    git $*
fi

# Remove the alt remote
git remote remove alt