#!/bin/bash

#
# git-comp: A Simple wrapper script to be used at competitions.
# This script allows the use of an alternate repository.
#

# The competition repository.
COMP_REPO=git@192.168.0.100:\~/FRC6090-2019
# The password to the remote. The server is configured to have a password
# of "1" because it is simple and easy to type.
COMP_PASS=1

# Add the alt remote
git remote add alt $COMP_REPO

# Fetch the current branch
CURRENT_BRANCH=$(git branch | grep "*" | cut -c 3-)

#
# Add the alt options
#
if [ "$1" == "push" ]; then
    echo "PASSWORD: $COMP_PASS"
    git push alt $CURRENT_BRANCH
elif [ "$1" == "pull" ]; then
    echo "PASSWORD: $COMP_PASS"
    git pull alt $CURRENT_BRANCH
else
    git $*
fi

# Remove the alt remote
git remote remove alt