version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/FRC6090-2019
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew downloadAll --info
      - run: ./gradlew build --info
