version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ls
      - run: ./gradlew build
      - run: ls && ls build
